name: Run validation and build checks

on:
  workflow_dispatch:
  pull_request:
    types:
    - assigned
  push:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run check
      run: make check

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Update the theme #shouldnt be necessary
      run: make update-themes
  
    - name: Render site
      run: make build
